name: CLDE-Hangman

services:
  hangman-frontend:
    build:
      context: .
      dockerfile: docker/frontend/dockerfile
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - hangman
    depends_on:
      - hangman-server
  hangman-server:
    build:
      context: .
      dockerfile: docker/backend/dockerfile
    restart: unless-stopped
    ports:
    - "3000:3000"
    environment:
    - PORT=3000
    - HOST=0.0.0.0
    - NODE_ENV=production
    - FRONTEND_ORIGIN=https://hangman.hipstertech.ch
    - DB_HOST=hangman-mysql
    - DB_PORT=3306
    - DB_USER=hangman
    - DB_PASSWORD=${DB_PW}
    - DB_NAME=hangman_game
    networks:
    - hangman
    depends_on:
      - hangman-mysql

  hangman-mysql:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=hangman_game
      - MYSQL_USER=hangman
      - MYSQL_PASSWORD=${DB_PW}
    networks:
      - hangman
    volumes:
      - db-data:/var/lib/mysql

networks:
  hangman:

volumes:
  db-data: